export const countryNames: Record<string, Record<string, string>> = {
  "Afghanistan": { it: "Afghanistan", en: "Afghanistan", fr: "Afghanistan", es: "Afganistán", de: "Afghanistan" },
  "Albania": { it: "Albania", en: "Albania", fr: "Albanie", es: "Albania", de: "Albanien" },
  "Algeria": { it: "Algeria", en: "Algeria", fr: "Algérie", es: "Argelia", de: "Algerien" },
  "Andorra": { it: "Andorra", en: "Andorra", fr: "Andorre", es: "Andorra", de: "Andorra" },
  "Angola": { it: "Angola", en: "Angola", fr: "Angola", es: "Angola", de: "Angola" },
  "Antigua and Barbuda": { it: "Antigua e Barbuda", en: "Antigua and Barbuda", fr: "Antigua-et-Barbuda", es: "Antigua y Barbuda", de: "Antigua und Barbuda" },
  "Argentina": { it: "Argentina", en: "Argentina", fr: "Argentine", es: "Argentina", de: "Argentinien" },
  "Armenia": { it: "Armenia", en: "Armenia", fr: "Arménie", es: "Armenia", de: "Armenien" },
  "Australia": { it: "Australia", en: "Australia", fr: "Australie", es: "Australia", de: "Australien" },
  "Austria": { it: "Austria", en: "Austria", fr: "Autriche", es: "Austria", de: "Österreich" },
  "Azerbaijan": { it: "Azerbaigian", en: "Azerbaijan", fr: "Azerbaïdjan", es: "Azerbaiyán", de: "Aserbaidschan" },
  "Bahamas": { it: "Bahamas", en: "Bahamas", fr: "Bahamas", es: "Bahamas", de: "Bahamas" },
  "Bahrain": { it: "Bahrein", en: "Bahrain", fr: "Bahreïn", es: "Baréin", de: "Bahrain" },
  "Bangladesh": { it: "Bangladesh", en: "Bangladesh", fr: "Bangladesh", es: "Bangladés", de: "Bangladesch" },
  "Barbados": { it: "Barbados", en: "Barbados", fr: "Barbade", es: "Barbados", de: "Barbados" },
  "Belarus": { it: "Bielorussia", en: "Belarus", fr: "Biélorussie", es: "Bielorrusia", de: "Belarus" },
  "Belgium": { it: "Belgio", en: "Belgium", fr: "Belgique", es: "Bélgica", de: "Belgien" },
  "Belize": { it: "Belize", en: "Belize", fr: "Belize", es: "Belice", de: "Belize" },
  "Benin": { it: "Benin", en: "Benin", fr: "Bénin", es: "Benín", de: "Benin" },
  "Bhutan": { it: "Bhutan", en: "Bhutan", fr: "Bhoutan", es: "Bután", de: "Bhutan" },
  "Bolivia": { it: "Bolivia", en: "Bolivia", fr: "Bolivie", es: "Bolivia", de: "Bolivien" },
  "Bosnia and Herzegovina": { it: "Bosnia ed Erzegovina", en: "Bosnia and Herzegovina", fr: "Bosnie-Herzégovine", es: "Bosnia y Herzegovina", de: "Bosnien und Herzegowina" },
  "Botswana": { it: "Botswana", en: "Botswana", fr: "Botswana", es: "Botsuana", de: "Botswana" },
  "Brazil": { it: "Brasile", en: "Brazil", fr: "Brésil", es: "Brasil", de: "Brasilien" },
  "Brunei": { it: "Brunei", en: "Brunei", fr: "Brunei", es: "Brunéi", de: "Brunei" },
  "Bulgaria": { it: "Bulgaria", en: "Bulgaria", fr: "Bulgarie", es: "Bulgaria", de: "Bulgarien" },
  "Burkina Faso": { it: "Burkina Faso", en: "Burkina Faso", fr: "Burkina Faso", es: "Burkina Faso", de: "Burkina Faso" },
  "Burundi": { it: "Burundi", en: "Burundi", fr: "Burundi", es: "Burundi", de: "Burundi" },
  "Cabo Verde": { it: "Capo Verde", en: "Cabo Verde", fr: "Cap-Vert", es: "Cabo Verde", de: "Kap Verde" },
  "Cambodia": { it: "Cambogia", en: "Cambodia", fr: "Cambodge", es: "Camboya", de: "Kambodscha" },
  "Cameroon": { it: "Camerun", en: "Cameroon", fr: "Cameroun", es: "Camerún", de: "Kamerun" },
  "Canada": { it: "Canada", en: "Canada", fr: "Canada", es: "Canadá", de: "Kanada" },
  "Central African Republic": { it: "Repubblica Centrafricana", en: "Central African Republic", fr: "République centrafricaine", es: "República Centroafricana", de: "Zentralafrikanische Republik" },
  "Chad": { it: "Ciad", en: "Chad", fr: "Tchad", es: "Chad", de: "Tschad" },
  "Chile": { it: "Cile", en: "Chile", fr: "Chili", es: "Chile", de: "Chile" },
  "China": { it: "Cina", en: "China", fr: "Chine", es: "China", de: "China" },
  "Colombia": { it: "Colombia", en: "Colombia", fr: "Colombie", es: "Colombia", de: "Kolumbien" },
  "Comoros": { it: "Comore", en: "Comoros", fr: "Comores", es: "Comoras", de: "Komoren" },
  "Congo": { it: "Congo", en: "Congo", fr: "Congo", es: "Congo", de: "Kongo" },
  "Costa Rica": { it: "Costa Rica", en: "Costa Rica", fr: "Costa Rica", es: "Costa Rica", de: "Costa Rica" },
  "Croatia": { it: "Croazia", en: "Croatia", fr: "Croatie", es: "Croacia", de: "Kroatien" },
  "Cuba": { it: "Cuba", en: "Cuba", fr: "Cuba", es: "Cuba", de: "Kuba" },
  "Cyprus": { it: "Cipro", en: "Cyprus", fr: "Chypre", es: "Chipre", de: "Zypern" },
  "Czech Republic": { it: "Repubblica Ceca", en: "Czech Republic", fr: "République tchèque", es: "República Checa", de: "Tschechien" },
  "Denmark": { it: "Danimarca", en: "Denmark", fr: "Danemark", es: "Dinamarca", de: "Dänemark" },
  "Djibouti": { it: "Gibuti", en: "Djibouti", fr: "Djibouti", es: "Yibuti", de: "Dschibuti" },
  "Dominica": { it: "Dominica", en: "Dominica", fr: "Dominique", es: "Dominica", de: "Dominica" },
  "Dominican Republic": { it: "Repubblica Dominicana", en: "Dominican Republic", fr: "République dominicaine", es: "República Dominicana", de: "Dominikanische Republik" },
  "Ecuador": { it: "Ecuador", en: "Ecuador", fr: "Équateur", es: "Ecuador", de: "Ecuador" },
  "Egypt": { it: "Egitto", en: "Egypt", fr: "Égypte", es: "Egipto", de: "Ägypten" },
  "El Salvador": { it: "El Salvador", en: "El Salvador", fr: "Salvador", es: "El Salvador", de: "El Salvador" },
  "Equatorial Guinea": { it: "Guinea Equatoriale", en: "Equatorial Guinea", fr: "Guinée équatoriale", es: "Guinea Ecuatorial", de: "Äquatorialguinea" },
  "Eritrea": { it: "Eritrea", en: "Eritrea", fr: "Érythrée", es: "Eritrea", de: "Eritrea" },
  "Estonia": { it: "Estonia", en: "Estonia", fr: "Estonie", es: "Estonia", de: "Estland" },
  "Eswatini": { it: "Eswatini", en: "Eswatini", fr: "Eswatini", es: "Esuatini", de: "Eswatini" },
  "Ethiopia": { it: "Etiopia", en: "Ethiopia", fr: "Éthiopie", es: "Etiopía", de: "Äthiopien" },
  "Fiji": { it: "Figi", en: "Fiji", fr: "Fidji", es: "Fiyi", de: "Fidschi" },
  "Finland": { it: "Finlandia", en: "Finland", fr: "Finlande", es: "Finlandia", de: "Finnland" },
  "France": { it: "Francia", en: "France", fr: "France", es: "Francia", de: "Frankreich" },
  "Gabon": { it: "Gabon", en: "Gabon", fr: "Gabon", es: "Gabón", de: "Gabun" },
  "Gambia": { it: "Gambia", en: "Gambia", fr: "Gambie", es: "Gambia", de: "Gambia" },
  "Georgia": { it: "Georgia", en: "Georgia", fr: "Géorgie", es: "Georgia", de: "Georgien" },
  "Germany": { it: "Germania", en: "Germany", fr: "Allemagne", es: "Alemania", de: "Deutschland" },
  "Ghana": { it: "Ghana", en: "Ghana", fr: "Ghana", es: "Ghana", de: "Ghana" },
  "Greece": { it: "Grecia", en: "Greece", fr: "Grèce", es: "Grecia", de: "Griechenland" },
  "Grenada": { it: "Grenada", en: "Grenada", fr: "Grenade", es: "Granada", de: "Grenada" },
  "Guatemala": { it: "Guatemala", en: "Guatemala", fr: "Guatemala", es: "Guatemala", de: "Guatemala" },
  "Guinea": { it: "Guinea", en: "Guinea", fr: "Guinée", es: "Guinea", de: "Guinea" },
  "Guinea-Bissau": { it: "Guinea-Bissau", en: "Guinea-Bissau", fr: "Guinée-Bissau", es: "Guinea-Bisáu", de: "Guinea-Bissau" },
  "Guyana": { it: "Guyana", en: "Guyana", fr: "Guyana", es: "Guyana", de: "Guyana" },
  "Haiti": { it: "Haiti", en: "Haiti", fr: "Haïti", es: "Haití", de: "Haiti" },
  "Honduras": { it: "Honduras", en: "Honduras", fr: "Honduras", es: "Honduras", de: "Honduras" },
  "Hungary": { it: "Ungheria", en: "Hungary", fr: "Hongrie", es: "Hungría", de: "Ungarn" },
  "Iceland": { it: "Islanda", en: "Iceland", fr: "Islande", es: "Islandia", de: "Island" },
  "India": { it: "India", en: "India", fr: "Inde", es: "India", de: "Indien" },
  "Indonesia": { it: "Indonesia", en: "Indonesia", fr: "Indonésie", es: "Indonesia", de: "Indonesien" },
  "Iran": { it: "Iran", en: "Iran", fr: "Iran", es: "Irán", de: "Iran" },
  "Iraq": { it: "Iraq", en: "Iraq", fr: "Irak", es: "Irak", de: "Irak" },
  "Ireland": { it: "Irlanda", en: "Ireland", fr: "Irlande", es: "Irlanda", de: "Irland" },
  "Israel": { it: "Israele", en: "Israel", fr: "Israël", es: "Israel", de: "Israel" },
  "Italy": { it: "Italia", en: "Italy", fr: "Italie", es: "Italia", de: "Italien" },
  "Jamaica": { it: "Giamaica", en: "Jamaica", fr: "Jamaïque", es: "Jamaica", de: "Jamaika" },
  "Japan": { it: "Giappone", en: "Japan", fr: "Japon", es: "Japón", de: "Japan" },
  "Jordan": { it: "Giordania", en: "Jordan", fr: "Jordanie", es: "Jordania", de: "Jordanien" },
  "Kazakhstan": { it: "Kazakistan", en: "Kazakhstan", fr: "Kazakhstan", es: "Kazajistán", de: "Kasachstan" },
  "Kenya": { it: "Kenya", en: "Kenya", fr: "Kenya", es: "Kenia", de: "Kenia" },
  "Kiribati": { it: "Kiribati", en: "Kiribati", fr: "Kiribati", es: "Kiribati", de: "Kiribati" },
  "Korea, North": { it: "Corea del Nord", en: "Korea, North", fr: "Corée du Nord", es: "Corea del Norte", de: "Nordkorea" },
  "Korea, South": { it: "Corea del Sud", en: "Korea, South", fr: "Corée du Sud", es: "Corea del Sur", de: "Südkorea" },
  "Kuwait": { it: "Kuwait", en: "Kuwait", fr: "Koweït", es: "Kuwait", de: "Kuwait" },
  "Kyrgyzstan": { it: "Kirghizistan", en: "Kyrgyzstan", fr: "Kirghizistan", es: "Kirguistán", de: "Kirgisistan" },
  "Laos": { it: "Laos", en: "Laos", fr: "Laos", es: "Laos", de: "Laos" },
  "Latvia": { it: "Lettonia", en: "Latvia", fr: "Lettonie", es: "Letonia", de: "Lettland" },
  "Lebanon": { it: "Libano", en: "Lebanon", fr: "Liban", es: "Líbano", de: "Libanon" },
  "Lesotho": { it: "Lesotho", en: "Lesotho", fr: "Lesotho", es: "Lesoto", de: "Lesotho" },
  "Liberia": { it: "Liberia", en: "Liberia", fr: "Liberia", es: "Liberia", de: "Liberia" },
  "Libya": { it: "Libia", en: "Libya", fr: "Libye", es: "Libia", de: "Libyen" },
  "Liechtenstein": { it: "Liechtenstein", en: "Liechtenstein", fr: "Liechtenstein", es: "Liechtenstein", de: "Liechtenstein" },
  "Lithuania": { it: "Lituania", en: "Lithuania", fr: "Lituanie", es: "Lituania", de: "Litauen" },
  "Luxembourg": { it: "Lussemburgo", en: "Luxembourg", fr: "Luxembourg", es: "Luxemburgo", de: "Luxemburg" },
  "Madagascar": { it: "Madagascar", en: "Madagascar", fr: "Madagascar", es: "Madagascar", de: "Madagaskar" },
  "Malawi": { it: "Malawi", en: "Malawi", fr: "Malawi", es: "Malaui", de: "Malawi" },
  "Malaysia": { it: "Malaysia", en: "Malaysia", fr: "Malaisie", es: "Malasia", de: "Malaysia" },
  "Maldives": { it: "Maldive", en: "Maldives", fr: "Maldives", es: "Maldivas", de: "Malediven" },
  "Mali": { it: "Mali", en: "Mali", fr: "Mali", es: "Malí", de: "Mali" },
  "Malta": { it: "Malta", en: "Malta", fr: "Malte", es: "Malta", de: "Malta" },
  "Marshall Islands": { it: "Isole Marshall", en: "Marshall Islands", fr: "Îles Marshall", es: "Islas Marshall", de: "Marshallinseln" },
  "Mauritania": { it: "Mauritania", en: "Mauritania", fr: "Mauritanie", es: "Mauritania", de: "Mauretanien" },
  "Mauritius": { it: "Mauritius", en: "Mauritius", fr: "Maurice", es: "Mauricio", de: "Mauritius" },
  "Mexico": { it: "Messico", en: "Mexico", fr: "Mexique", es: "México", de: "Mexiko" },
  "Micronesia": { it: "Micronesia", en: "Micronesia", fr: "Micronésie", es: "Micronesia", de: "Mikronesien" },
  "Moldova": { it: "Moldavia", en: "Moldova", fr: "Moldavie", es: "Moldavia", de: "Moldau" },
  "Monaco": { it: "Monaco", en: "Monaco", fr: "Monaco", es: "Mónaco", de: "Monaco" },
  "Mongolia": { it: "Mongolia", en: "Mongolia", fr: "Mongolie", es: "Mongolia", de: "Mongolei" },
  "Montenegro": { it: "Montenegro", en: "Montenegro", fr: "Monténégro", es: "Montenegro", de: "Montenegro" },
  "Morocco": { it: "Marocco", en: "Morocco", fr: "Maroc", es: "Marruecos", de: "Marokko" },
  "Mozambique": { it: "Mozambico", en: "Mozambique", fr: "Mozambique", es: "Mozambique", de: "Mosambik" },
  "Myanmar": { it: "Myanmar", en: "Myanmar", fr: "Myanmar", es: "Myanmar", de: "Myanmar" },
  "Namibia": { it: "Namibia", en: "Namibia", fr: "Namibie", es: "Namibia", de: "Namibia" },
  "Nauru": { it: "Nauru", en: "Nauru", fr: "Nauru", es: "Nauru", de: "Nauru" },
  "Nepal": { it: "Nepal", en: "Nepal", fr: "Népal", es: "Nepal", de: "Nepal" },
  "Netherlands": { it: "Paesi Bassi", en: "Netherlands", fr: "Pays-Bas", es: "Países Bajos", de: "Niederlande" },
  "New Zealand": { it: "Nuova Zelanda", en: "New Zealand", fr: "Nouvelle-Zélande", es: "Nueva Zelanda", de: "Neuseeland" },
  "Nicaragua": { it: "Nicaragua", en: "Nicaragua", fr: "Nicaragua", es: "Nicaragua", de: "Nicaragua" },
  "Niger": { it: "Niger", en: "Niger", fr: "Niger", es: "Níger", de: "Niger" },
  "Nigeria": { it: "Nigeria", en: "Nigeria", fr: "Nigeria", es: "Nigeria", de: "Nigeria" },
  "North Macedonia": { it: "Macedonia del Nord", en: "North Macedonia", fr: "Macédoine du Nord", es: "Macedonia del Norte", de: "Nordmazedonien" },
  "Norway": { it: "Norvegia", en: "Norway", fr: "Norvège", es: "Noruega", de: "Norwegen" },
  "Oman": { it: "Oman", en: "Oman", fr: "Oman", es: "Omán", de: "Oman" },
  "Pakistan": { it: "Pakistan", en: "Pakistan", fr: "Pakistan", es: "Pakistán", de: "Pakistan" },
  "Palau": { it: "Palau", en: "Palau", fr: "Palaos", es: "Palaos", de: "Palau" },
  "Panama": { it: "Panama", en: "Panama", fr: "Panama", es: "Panamá", de: "Panama" },
  "Papua New Guinea": { it: "Papua Nuova Guinea", en: "Papua New Guinea", fr: "Papouasie-Nouvelle-Guinée", es: "Papúa Nueva Guinea", de: "Papua-Neuguinea" },
  "Paraguay": { it: "Paraguay", en: "Paraguay", fr: "Paraguay", es: "Paraguay", de: "Paraguay" },
  "Peru": { it: "Perù", en: "Peru", fr: "Pérou", es: "Perú", de: "Peru" },
  "Philippines": { it: "Filippine", en: "Philippines", fr: "Philippines", es: "Filipinas", de: "Philippinen" },
  "Poland": { it: "Polonia", en: "Poland", fr: "Pologne", es: "Polonia", de: "Polen" },
  "Portugal": { it: "Portogallo", en: "Portugal", fr: "Portugal", es: "Portugal", de: "Portugal" },
  "Qatar": { it: "Qatar", en: "Qatar", fr: "Qatar", es: "Catar", de: "Katar" },
  "Romania": { it: "Romania", en: "Romania", fr: "Roumanie", es: "Rumanía", de: "Rumänien" },
  "Russia": { it: "Russia", en: "Russia", fr: "Russie", es: "Rusia", de: "Russland" },
  "Rwanda": { it: "Ruanda", en: "Rwanda", fr: "Rwanda", es: "Ruanda", de: "Ruanda" },
  "Saint Kitts and Nevis": { it: "Saint Kitts e Nevis", en: "Saint Kitts and Nevis", fr: "Saint-Kitts-et-Nevis", es: "San Cristóbal y Nieves", de: "St. Kitts und Nevis" },
  "Saint Lucia": { it: "Santa Lucia", en: "Saint Lucia", fr: "Sainte-Lucie", es: "Santa Lucía", de: "St. Lucia" },
  "Saint Vincent and the Grenadines": { it: "Saint Vincent e Grenadine", en: "Saint Vincent and the Grenadines", fr: "Saint-Vincent-et-les-Grenadines", es: "San Vicente y las Granadinas", de: "St. Vincent und die Grenadinen" },
  "Samoa": { it: "Samoa", en: "Samoa", fr: "Samoa", es: "Samoa", de: "Samoa" },
  "San Marino": { it: "San Marino", en: "San Marino", fr: "Saint-Marin", es: "San Marino", de: "San Marino" },
  "Sao Tome and Principe": { it: "São Tomé e Príncipe", en: "Sao Tome and Principe", fr: "Sao Tomé-et-Príncipe", es: "Santo Tomé y Príncipe", de: "São Tomé und Príncipe" },
  "Saudi Arabia": { it: "Arabia Saudita", en: "Saudi Arabia", fr: "Arabie saoudite", es: "Arabia Saudita", de: "Saudi-Arabien" },
  "Senegal": { it: "Senegal", en: "Senegal", fr: "Sénégal", es: "Senegal", de: "Senegal" },
  "Serbia": { it: "Serbia", en: "Serbia", fr: "Serbie", es: "Serbia", de: "Serbien" },
  "Seychelles": { it: "Seychelles", en: "Seychelles", fr: "Seychelles", es: "Seychelles", de: "Seychellen" },
  "Sierra Leone": { it: "Sierra Leone", en: "Sierra Leone", fr: "Sierra Leone", es: "Sierra Leona", de: "Sierra Leone" },
  "Singapore": { it: "Singapore", en: "Singapore", fr: "Singapour", es: "Singapur", de: "Singapur" },
  "Slovakia": { it: "Slovacchia", en: "Slovakia", fr: "Slovaquie", es: "Eslovaquia", de: "Slowakei" },
  "Slovenia": { it: "Slovenia", en: "Slovenia", fr: "Slovénie", es: "Eslovenia", de: "Slowenien" },
  "Solomon Islands": { it: "Isole Salomone", en: "Solomon Islands", fr: "Îles Salomon", es: "Islas Salomón", de: "Salomonen" },
  "Somalia": { it: "Somalia", en: "Somalia", fr: "Somalie", es: "Somalia", de: "Somalia" },
  "South Africa": { it: "Sudafrica", en: "South Africa", fr: "Afrique du Sud", es: "Sudáfrica", de: "Südafrika" },
  "South Sudan": { it: "Sudan del Sud", en: "South Sudan", fr: "Soudan du Sud", es: "Sudán del Sur", de: "Südsudan" },
  "Spain": { it: "Spagna", en: "Spain", fr: "Espagne", es: "España", de: "Spanien" },
  "Sri Lanka": { it: "Sri Lanka", en: "Sri Lanka", fr: "Sri Lanka", es: "Sri Lanka", de: "Sri Lanka" },
  "Sudan": { it: "Sudan", en: "Sudan", fr: "Soudan", es: "Sudán", de: "Sudan" },
  "Suriname": { it: "Suriname", en: "Suriname", fr: "Suriname", es: "Surinam", de: "Suriname" },
  "Sweden": { it: "Svezia", en: "Sweden", fr: "Suède", es: "Suecia", de: "Schweden" },
  "Switzerland": { it: "Svizzera", en: "Switzerland", fr: "Suisse", es: "Suiza", de: "Schweiz" },
  "Syria": { it: "Siria", en: "Syria", fr: "Syrie", es: "Siria", de: "Syrien" },
  "Taiwan": { it: "Taiwan", en: "Taiwan", fr: "Taïwan", es: "Taiwán", de: "Taiwan" },
  "Tajikistan": { it: "Tagikistan", en: "Tajikistan", fr: "Tadjikistan", es: "Tayikistán", de: "Tadschikistan" },
  "Tanzania": { it: "Tanzania", en: "Tanzania", fr: "Tanzanie", es: "Tanzania", de: "Tansania" },
  "Thailand": { it: "Thailandia", en: "Thailand", fr: "Thaïlande", es: "Tailandia", de: "Thailand" },
  "Timor-Leste": { it: "Timor Est", en: "Timor-Leste", fr: "Timor oriental", es: "Timor Oriental", de: "Osttimor" },
  "Togo": { it: "Togo", en: "Togo", fr: "Togo", es: "Togo", de: "Togo" },
  "Tonga": { it: "Tonga", en: "Tonga", fr: "Tonga", es: "Tonga", de: "Tonga" },
  "Trinidad and Tobago": { it: "Trinidad e Tobago", en: "Trinidad and Tobago", fr: "Trinité-et-Tobago", es: "Trinidad y Tobago", de: "Trinidad und Tobago" },
  "Tunisia": { it: "Tunisia", en: "Tunisia", fr: "Tunisie", es: "Túnez", de: "Tunesien" },
  "Turkey": { it: "Turchia", en: "Turkey", fr: "Turquie", es: "Turquía", de: "Türkei" },
  "Turkmenistan": { it: "Turkmenistan", en: "Turkmenistan", fr: "Turkménistan", es: "Turkmenistán", de: "Turkmenistan" },
  "Tuvalu": { it: "Tuvalu", en: "Tuvalu", fr: "Tuvalu", es: "Tuvalu", de: "Tuvalu" },
  "Uganda": { it: "Uganda", en: "Uganda", fr: "Ouganda", es: "Uganda", de: "Uganda" },
  "Ukraine": { it: "Ucraina", en: "Ukraine", fr: "Ukraine", es: "Ucrania", de: "Ukraine" },
  "United Arab Emirates": { it: "Emirati Arabi Uniti", en: "United Arab Emirates", fr: "Émirats arabes unis", es: "Emiratos Árabes Unidos", de: "Vereinigte Arabische Emirate" },
  "United Kingdom": { it: "Regno Unito", en: "United Kingdom", fr: "Royaume-Uni", es: "Reino Unido", de: "Vereinigtes Königreich" },
  "United States": { it: "Stati Uniti", en: "United States", fr: "États-Unis", es: "Estados Unidos", de: "Vereinigte Staaten" },
  "Uruguay": { it: "Uruguay", en: "Uruguay", fr: "Uruguay", es: "Uruguay", de: "Uruguay" },
  "Uzbekistan": { it: "Uzbekistan", en: "Uzbekistan", fr: "Ouzbékistan", es: "Uzbekistán", de: "Usbekistan" },
  "Vanuatu": { it: "Vanuatu", en: "Vanuatu", fr: "Vanuatu", es: "Vanuatu", de: "Vanuatu" },
  "Vatican City": { it: "Città del Vaticano", en: "Vatican City", fr: "Cité du Vatican", es: "Ciudad del Vaticano", de: "Vatikanstadt" },
  "Venezuela": { it: "Venezuela", en: "Venezuela", fr: "Venezuela", es: "Venezuela", de: "Venezuela" },
  "Vietnam": { it: "Vietnam", en: "Vietnam", fr: "Viêt Nam", es: "Vietnam", de: "Vietnam" },
  "Yemen": { it: "Yemen", en: "Yemen", fr: "Yémen", es: "Yemen", de: "Jemen" },
  "Zambia": { it: "Zambia", en: "Zambia", fr: "Zambie", es: "Zambia", de: "Sambia" },
  "Zimbabwe": { it: "Zimbabwe", en: "Zimbabwe", fr: "Zimbabwe", es: "Zimbabue", de: "Simbabwe" },
};
